---
title: "Visualization 1"
author: "Jingqi Song"
date: "September 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r data_import,cache=TRUE}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## start a plot

```{r }
ggplot(weather_df,aes(x = tmin, y = tmax))+ 
  geom_point()
```

just focus on centralpark

```{r}
weather_df%>%
  filter(name == 'CentralPark_NY')%>%
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```

## more plot options


```{r}
ggplot(weather_df,aes(x = tmin, y = tmax))+ 
  geom_point(aes(color = name))
```

add a geom

```{r}
ggplot(weather_df,aes(x = tmin, y = tmax))+ 
  geom_point(aes(color = name))+
  geom_smooth(se = FALSE)
```

add some options

```{r}
ggplot(weather_df,aes(x = tmin, y = tmax))+ 
  geom_point(aes(color = name),alpha=0.4)+
  geom_smooth(se = FALSE)
```

global options

```{r}
ggplot(weather_df,aes(x = tmin, y = tmax,color = name))+ 
  geom_point(alpha=0.4)+
  geom_smooth(se = FALSE)
```

facetting...

```{r}
ggplot(weather_df,aes(x = tmin, y = tmax,color = name))+ 
  geom_point(alpha=0.4)+
  geom_smooth(se = FALSE)+
  facet_grid(~ name)
```

a more interesting plot

```{r}
ggplot(weather_df,aes(x = date, y = tmax,color = name, size = prcp))+ 
  geom_point()+
  geom_smooth(se = FALSE)+
  facet_grid(~ name)

```

## univariate plots

histogram
```{r}
ggplot(weather_df,aes(x = tmax))+ 
  geom_histogram(alpha=.5)

```

```{r}
ggplot(weather_df,aes(x = tmax,fill = name))+ 
  geom_density(alpha= .5)

```

```{r}
ggplot(weather_df,aes(x = tmax,y = name))+ 
  geom_ridges()

```











