---
title: "1004_eda"
author: "Jingqi Song"
date: "October 4, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.width=6,
  fig.asp=.6,
  out.width='90%'
)
library(tidyverse)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

data import

```{r import}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
weather_df
```

## start grouping

grouping structure is kind of invisible.
Groups:   name, month [36]
```{r}
weather_df %>% 
  group_by(name,month) %>% 
  ungroup
```

number for each group. count first
```{r setup, include=FALSE}
weather_df %>% 
  group_by(name,month) %>% 
  summarize(number = n())

weather_df %>% 
  group_by(name) %>% 
  summarize(number = n())

weather_df %>% 
  count(month)
```

## grouped summaries

```{r}
weather_df %>% 
  group_by(name,month) %>% 
  summarize(number = n(),
            num_na = sum(is.na(tmax)),
            mean_tmax = mean(tmax))

weather_df %>% 
  group_by(name,month) %>% 
  summarize(number = n(),
            mean_tmax = mean(tmax,na.rm = TRUE),
            median_prcp = median(prcp, na.rm=TRUE),
            sd_tmin = sd(tmin,na.rm=TRUE)
            )

```

still a tibble! plot
plot 2 tibbles at once

```{r}
weather_df %>% 
  group_by(name,month) %>% 
  summarize(number = n(),
            mean_tmax = mean(tmax,na.rm = TRUE),
            median_prcp = median(prcp, na.rm=TRUE),
            sd_tmin = sd(tmin,na.rm=TRUE)) %>% 
ggplot(aes(x=month,y=mean_tmax,color=name))+
  geom_point(alpha=.5)+
  geom_line(data=month_df,aes(x=month,y=mean_tmax))

```

tidy is best for humans...

```{r setup}
weather_df %>% 
  group_by(name,month) %>% 
  summarize(mean_tmax = mean(tmax,na.rm = TRUE)) %>% 
  spread(key=month,value=mean_tmax) 
```

## grouped mutate

```{r}
weather_df %>% 
  group_by(name,month) %>% 
  mutate(mean_tmax = mean(tmax,na.rm = TRUE)) 
```


```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(mean_tmax = mean(tmax,na.rm = TRUE),
         centered_tmax = tmax - mean_tmax) %>% 
  ggplot(aes(x=date, y=centered_tmax, color=name))+
  geom_point()
```

## window functions
rank of original numbers

```{r}
weather_df %>% 
  group_by(name, month) %>% 
  mutate(tmax_rank = min_rank(desc(tmax))) %>% 
  filter(tmax_rank < 2)
```

use lags:
previous value

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(lag_tmax = lag(tmax))
```

##how neat is this

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(one_day_change = tmax - lag(tmax)) %>% 
  summarize(sd_one_day_change = sd(one_day_change, na.rm=TRUE))
```




